version: '1'

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - dbnet
      
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    networks:
      - dbnet

  prefect:
    image: prefecthq/prefect
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - dbnet
    

volumes:
  cassandra-data:
  postgresql-data:
  jupyterlab-data:

networks:
  dbnet:
